version: '3.8'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      RPC_HTTP_URL: http://localhost:8545
      RPC_WS_URL: ws://localhost:8546
      PRIVATE_KEY: change_me
      SUBGRAPH_URL: http://localhost:8000/subgraphs/name/graph
      EPOCH_MANAGER_ADDR: 0x0000000000000000000000000000000000000000
      VAULT_ADDR: 0x0000000000000000000000000000000000000000
      CHAIN_ID: 1
      HTTP_PORT: 8080
